import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import FetchData from './fetchData';
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: any) {
  return (
    <>
      {/* <Header /> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
{/*           
          <div>
            <a
              href="https://www.ocode.co/"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/ocodelogo.png"
                alt="Ocode Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div> */}
        </div>

        <div className={styles.center}>

          <div className="container">
            <div className="row">
              <div className="col-lg-3">
                <div className="section">
                  <div className="logo">
                    <Image src="/ui_ux_image.png"
                      alt="ui_ux"
                      width={100}
                      height={70}
                    />
                    <a
                      href="https://www.ocode.co/"
                      className={styles.card}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <h2>
                        UI / UX Design
                      </h2>
                      <p>
                        Find in-depth information about Next.js features and&nbsp;API.
                      </p>
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-lg-3">
                <div className="section">
                  <div className="logo">
                    <Image src="/ui_ux_image.png"
                      alt="ui_ux"
                      width={100}
                      height={70}
                    />
                    <a
                      href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                      className={styles.card}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <h2>
                        Mobile Apps
                      </h2>
                      <p>
                        Find in-depth information about Next.js features and&nbsp;API.
                      </p>
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-lg-3">
                <div className="section">
                  <div className="logo">
                    <Image src="/ui_ux_image.png"
                      alt="ui_ux"
                      width={100}
                      height={70}
                    />
                    <a
                      href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                      className={styles.card}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <h2>
                        Software Integration
                      </h2>
                      <p>
                        Find in-depth information about Next.js features and&nbsp;API.
                      </p>
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-lg-3">
                <div className="section">
                  <div className="logo">
                    <Image src="/ui_ux_image.png"
                      alt="ui_ux"
                      width={100}
                      height={70}
                    />
                    <a
                      href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                      className={styles.card}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <h2>
                        Progressive Web Apps
                      </h2>
                      <p>
                        Find in-depth information about Next.js features and&nbsp;API.
                      </p>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>



         
        </div>

       

        {
          data?.map((post: any, index: any) => {
            return (
              <li key={post.id}>
                <Link href={`/post/${post.id}`}>
                  {post.title}
                </Link>
              </li>)
          })
        }

      </main>
      {/* <Footer /> */}
    </>
  );
}


export async function getStaticProps() {

  const res = await fetch("https://jsonplaceholder.typicode.com/posts/");

  const data = await res.json();

  return {
    props: {
      data
    }
  }

}